   set echo on
SPOOL ca_schema_output.txt

--student id: 35672722
--student name: Ren Tong Low

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-02 22:42:21 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE bin_catalogue CASCADE CONSTRAINTS;

DROP TABLE collection_bin CASCADE CONSTRAINTS;

DROP TABLE collection_run CASCADE CONSTRAINTS;

DROP TABLE contract CASCADE CONSTRAINTS;

DROP TABLE contract_bin_pricing CASCADE CONSTRAINTS;

DROP TABLE contract_waste CASCADE CONSTRAINTS;

DROP TABLE local_authority CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE physical_bin CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE property_ownership CASCADE CONSTRAINTS;

DROP TABLE street CASCADE CONSTRAINTS;

DROP TABLE truck CASCADE CONSTRAINTS;

DROP TABLE waste_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bin_catalogue (
    binctl_size                 NUMBER(7,2) NOT NULL,
    binctl_standard_supply_cost NUMBER(7,2) NOT NULL,
    waste_type_id               NUMBER(7) NOT NULL,
    binctl_id                   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN bin_catalogue.binctl_size IS
    'bin size';

COMMENT ON COLUMN bin_catalogue.binctl_standard_supply_cost IS
    'standard supply cost';

COMMENT ON COLUMN bin_catalogue.waste_type_id IS
    'waste type id';

COMMENT ON COLUMN bin_catalogue.binctl_id IS
    'bin catalogue id';

ALTER TABLE bin_catalogue ADD CONSTRAINT bin_catalogue_pk PRIMARY KEY ( binctl_id );

ALTER TABLE bin_catalogue ADD CONSTRAINT bin_catalogue_nk UNIQUE ( binctl_size,
                                                                   waste_type_id );

CREATE TABLE collection_bin (
    collbin_kgs        NUMBER(7,2),
    collbin_overweight CHAR(1) NOT NULL,
    collbin_rfid       CHAR(24) NOT NULL,
    collrun_id         NUMBER(7) NOT NULL
);

ALTER TABLE collection_bin
    ADD CHECK ( collbin_overweight IN ( 'N',
                                        'Y' ) );

COMMENT ON COLUMN collection_bin.collbin_kgs IS
    'collected kg of the bin';

COMMENT ON COLUMN collection_bin.collbin_overweight IS
    'overweight';

COMMENT ON COLUMN collection_bin.collbin_rfid IS
    'bin RFID tag';

COMMENT ON COLUMN collection_bin.collrun_id IS
    'collection run id';

ALTER TABLE collection_bin ADD CONSTRAINT collection_detail_pk PRIMARY KEY ( collrun_id
,
                                                                             collbin_rfid
                                                                             );

CREATE TABLE collection_run (
    collrun_date DATE NOT NULL,
    truck_rego   VARCHAR2(50) NOT NULL,
    truck_vin    VARCHAR2(20) NOT NULL,
    collrun_id   NUMBER(7) NOT NULL,
    ctwaste_id   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN collection_run.collrun_date IS
    'date of collection';

COMMENT ON COLUMN collection_run.truck_rego IS
    'truck rego';

COMMENT ON COLUMN collection_run.truck_vin IS
    'truck vin';

COMMENT ON COLUMN collection_run.collrun_id IS
    'collection run id';

COMMENT ON COLUMN collection_run.ctwaste_id IS
    'contract waste id';

ALTER TABLE collection_run ADD CONSTRAINT collection_run_pk PRIMARY KEY ( collrun_id )
;

ALTER TABLE collection_run ADD CONSTRAINT collection_run_nk UNIQUE ( collrun_date );

CREATE TABLE contract (
    contract_no         NUMBER(7) NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date   DATE NOT NULL,
    lcaut_name          VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN contract.contract_no IS
    'contract no';

COMMENT ON COLUMN contract.contract_start_date IS
    'start date';

COMMENT ON COLUMN contract.contract_end_date IS
    'end date';

COMMENT ON COLUMN contract.lcaut_name IS
    'authority name';

ALTER TABLE contract ADD CONSTRAINT contract_pk PRIMARY KEY ( contract_no );

CREATE TABLE contract_bin_pricing (
    ctbinpri_supply_cost NUMBER(10,2) NOT NULL,
    ctwaste_id           NUMBER(7) NOT NULL,
    binctl_id            NUMBER(7) NOT NULL,
    ctbinpri_id          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN contract_bin_pricing.ctbinpri_supply_cost IS
    'contract supply cost';

COMMENT ON COLUMN contract_bin_pricing.ctwaste_id IS
    'contract waste id';

COMMENT ON COLUMN contract_bin_pricing.binctl_id IS
    'bin catalogue id';

COMMENT ON COLUMN contract_bin_pricing.ctbinpri_id IS
    'contract bin pricing id';

ALTER TABLE contract_bin_pricing ADD CONSTRAINT contract_bin_pricing_pk PRIMARY KEY (
ctbinpri_id );

ALTER TABLE contract_bin_pricing ADD CONSTRAINT contract_bin_pricing_nk UNIQUE ( ctwaste_id
,
                                                                                 binctl_id
                                                                                 );

CREATE TABLE contract_waste (
    ctwaste_coll_cost_per_kg NUMBER(7,2) NOT NULL,
    contract_no              NUMBER(7) NOT NULL,
    waste_type_id            NUMBER(7) NOT NULL,
    ctwaste_frequency        VARCHAR2(50) NOT NULL,
    ctwaste_id               NUMBER(7) NOT NULL
);

COMMENT ON COLUMN contract_waste.ctwaste_coll_cost_per_kg IS
    'collection cost per kg';

COMMENT ON COLUMN contract_waste.contract_no IS
    'contract no';

COMMENT ON COLUMN contract_waste.waste_type_id IS
    'waste type id';

COMMENT ON COLUMN contract_waste.ctwaste_frequency IS
    'collection frequency';

COMMENT ON COLUMN contract_waste.ctwaste_id IS
    'contract waste id';

ALTER TABLE contract_waste ADD CONSTRAINT contract_waste_pk PRIMARY KEY ( ctwaste_id )
;

ALTER TABLE contract_waste ADD CONSTRAINT contract_waste_nk UNIQUE ( waste_type_id,
                                                                     contract_no );

CREATE TABLE local_authority (
    lcaut_name             VARCHAR2(50) NOT NULL,
    lcaut_ceo_given_name   VARCHAR2(50) NOT NULL,
    lcaut_ceo_fam_name     VARCHAR2(50),
    lcaut_contact_phone_no VARCHAR2(20) NOT NULL,
    lcaut_total_area_sq_km NUMBER(7,2) NOT NULL,
    lcaut_type             VARCHAR2(20) NOT NULL
);

ALTER TABLE local_authority
    ADD
        CHECK ( lcaut_type IN ( 'Borough',
                                'City',
                                'District Council',
                                'Shire',
                                'Town' ) );

COMMENT ON COLUMN local_authority.lcaut_name IS
    'authority name';

COMMENT ON COLUMN local_authority.lcaut_ceo_given_name IS
    'ceo given name';

COMMENT ON COLUMN local_authority.lcaut_ceo_fam_name IS
    'ceo family name';

COMMENT ON COLUMN local_authority.lcaut_contact_phone_no IS
    'contact phone number';

COMMENT ON COLUMN local_authority.lcaut_total_area_sq_km IS
    'total area squares km';

ALTER TABLE local_authority ADD CONSTRAINT local_authority_pk PRIMARY KEY ( lcaut_name
);

CREATE TABLE owner (
    owner_id    NUMBER(7) NOT NULL,
    owner_name  VARCHAR2(50) NOT NULL,
    owner_email VARCHAR2(50) NOT NULL,
    owner_phone VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id';

COMMENT ON COLUMN owner.owner_name IS
    'owner name';

COMMENT ON COLUMN owner.owner_email IS
    'owner email';

COMMENT ON COLUMN owner.owner_phone IS
    'owner phone number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE physical_bin (
    collbin_rfid           CHAR(24) NOT NULL,
    physbin_supply_date    DATE NOT NULL,
    physbin_replace_reason VARCHAR2(50),
    property_id            NUMBER(7) NOT NULL,
    ctbinpri_id            NUMBER(7) NOT NULL
);

ALTER TABLE physical_bin
    ADD
        CHECK ( physbin_replace_reason IN ( 'Bin Failure',
                                            'Damaged by owner',
                                            'Damaged during pickup',
                                            'Stolen' ) );

COMMENT ON COLUMN physical_bin.collbin_rfid IS
    'bin RFID tag';

COMMENT ON COLUMN physical_bin.physbin_supply_date IS
    'bin supply date';

COMMENT ON COLUMN physical_bin.physbin_replace_reason IS
    'bin replacement reason';

COMMENT ON COLUMN physical_bin.property_id IS
    'property id (surrogate key)';

COMMENT ON COLUMN physical_bin.ctbinpri_id IS
    'contract bin pricing id';

ALTER TABLE physical_bin ADD CONSTRAINT physical_bin_pk PRIMARY KEY ( collbin_rfid );

CREATE TABLE property (
    property_id      NUMBER(7) NOT NULL,
    prop_street_no   NUMBER(7) NOT NULL,
    global_street_id NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.property_id IS
    'property id (surrogate key)';

COMMENT ON COLUMN property.prop_street_no IS
    'street number';

COMMENT ON COLUMN property.global_street_id IS
    'global street id';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( property_id );

ALTER TABLE property ADD CONSTRAINT property_nk UNIQUE ( prop_street_no,
                                                         global_street_id );

CREATE TABLE property_ownership (
    property_id NUMBER(7) NOT NULL,
    owner_id    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property_ownership.property_id IS
    'property id (surrogate key)';

COMMENT ON COLUMN property_ownership.owner_id IS
    'owner id';

ALTER TABLE property_ownership ADD CONSTRAINT property_ownership_pk PRIMARY KEY ( property_id
,
                                                                                owner_id
                                                                                );

CREATE TABLE street (
    street_id                NUMBER(7) NOT NULL,
    street_name              VARCHAR2(50) NOT NULL,
    street_length_m          NUMBER(7,2) NOT NULL,
    street_road_surface_type VARCHAR2(50) NOT NULL,
    street_no_of_lanes       NUMBER(7) NOT NULL,
    lcaut_name               VARCHAR2(50) NOT NULL,
    global_street_id         NUMBER(7) NOT NULL
);

ALTER TABLE street
    ADD
        CHECK ( street_road_surface_type IN ( 'Asphalt',
                                              'Concrete',
                                              'Unsealed' ) );

COMMENT ON COLUMN street.street_id IS
    'street id';

COMMENT ON COLUMN street.street_name IS
    'street bane';

COMMENT ON COLUMN street.street_length_m IS
    'length in metres';

COMMENT ON COLUMN street.street_no_of_lanes IS
    'number of lanes';

COMMENT ON COLUMN street.lcaut_name IS
    'authority name';

COMMENT ON COLUMN street.global_street_id IS
    'global street id';

ALTER TABLE street ADD CONSTRAINT street_pk PRIMARY KEY ( global_street_id );

ALTER TABLE street ADD CONSTRAINT street_nk UNIQUE ( street_id,
                                                     lcaut_name );

CREATE TABLE truck (
    truck_vin   VARCHAR2(20) NOT NULL,
    truck_make  VARCHAR2(50) NOT NULL,
    truck_model VARCHAR2(50) NOT NULL,
    truck_year  NUMBER(4) NOT NULL
);

COMMENT ON COLUMN truck.truck_vin IS
    'truck vin';

COMMENT ON COLUMN truck.truck_make IS
    'truck make';

COMMENT ON COLUMN truck.truck_model IS
    'truck model';

COMMENT ON COLUMN truck.truck_year IS
    'truck year';

ALTER TABLE truck ADD CONSTRAINT truck_pk PRIMARY KEY ( truck_vin );

CREATE TABLE waste_type (
    waste_type_id  NUMBER(7) NOT NULL,
    waste_type_des VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN waste_type.waste_type_id IS
    'waste type id';

COMMENT ON COLUMN waste_type.waste_type_des IS
    'waste type description';

ALTER TABLE waste_type ADD CONSTRAINT waste_type_pk PRIMARY KEY ( waste_type_id );

ALTER TABLE contract_bin_pricing
    ADD CONSTRAINT binct_ctbinpric_fk FOREIGN KEY ( binctl_id )
        REFERENCES bin_catalogue ( binctl_id );

ALTER TABLE collection_bin
    ADD CONSTRAINT collrun_colldetail_fk FOREIGN KEY ( collrun_id )
        REFERENCES collection_run ( collrun_id );

ALTER TABLE contract_waste
    ADD CONSTRAINT ct_ctwaste_fk FOREIGN KEY ( contract_no )
        REFERENCES contract ( contract_no );

ALTER TABLE physical_bin
    ADD CONSTRAINT ctbinpric_physicalbin_fk FOREIGN KEY ( ctbinpri_id )
        REFERENCES contract_bin_pricing ( ctbinpri_id );

ALTER TABLE collection_run
    ADD CONSTRAINT ctwaste_collrun_fk FOREIGN KEY ( ctwaste_id )
        REFERENCES contract_waste ( ctwaste_id );

ALTER TABLE contract_bin_pricing
    ADD CONSTRAINT ctwaste_ctbinpric_fk FOREIGN KEY ( ctwaste_id )
        REFERENCES contract_waste ( ctwaste_id );

ALTER TABLE contract
    ADD CONSTRAINT localaut_contract_fk FOREIGN KEY ( lcaut_name )
        REFERENCES local_authority ( lcaut_name );

ALTER TABLE street
    ADD CONSTRAINT localaut_street_fk FOREIGN KEY ( lcaut_name )
        REFERENCES local_authority ( lcaut_name );

ALTER TABLE property_ownership
    ADD CONSTRAINT owner_propowner FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE collection_bin
    ADD CONSTRAINT phybin_colldetial_fk FOREIGN KEY ( collbin_rfid )
        REFERENCES physical_bin ( collbin_rfid );

ALTER TABLE physical_bin
    ADD CONSTRAINT prop_physicalbin_fk FOREIGN KEY ( property_id )
        REFERENCES property ( property_id );

ALTER TABLE property_ownership
    ADD CONSTRAINT prop_propowner_fk FOREIGN KEY ( property_id )
        REFERENCES property ( property_id );

ALTER TABLE property
    ADD CONSTRAINT street_property_fk FOREIGN KEY ( global_street_id )
        REFERENCES street ( global_street_id );

ALTER TABLE collection_run
    ADD CONSTRAINT truck_collrun FOREIGN KEY ( truck_vin )
        REFERENCES truck ( truck_vin );

ALTER TABLE bin_catalogue
    ADD CONSTRAINT wastetype_binct FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );

ALTER TABLE contract_waste
    ADD CONSTRAINT wastetype_contractwaste_fk FOREIGN KEY ( waste_type_id )
        REFERENCES waste_type ( waste_type_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off